name: delete-untagged

# trigger events
on:
  # Manual
  workflow_dispatch:

jobs:
  delete-untagged:
    name: delete-untagged
    runs-on: ubuntu-latest
    steps:
      - name: 🗑️ Purge untagged packages from ghcr
        uses: dylanratcliffe/delete-untagged-containers@main
        with:
          package_name: laraondock
          user: sujaykumarh
          token: ${{ secrets.PAT_GITHUB }}
